package com.example.engine

import android.content.ContentValues
import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import android.graphics.PorterDuff
import android.graphics.PorterDuffXfermode
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import androidx.compose.ui.geometry.Offset
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import kotlin.math.abs
import kotlin.math.hypot
import kotlin.math.max
import kotlin.math.min
import kotlin.math.roundToInt
import kotlin.math.sqrt

enum class AutoDrawMode(
    val id: String,
    val title: String,
    val japaneseTag: String,
    val description: String,
    val defaultIntensity: Float
) {
    ORIGINAL(
        id = "ORIGINAL",
        title = "Original Reference",
        japaneseTag = "原画",
        description = "Unprocessed full-color reference image.",
        defaultIntensity = 0.5f
    ),
    EDGE_OUTLINE(
        id = "EDGE_OUTLINE",
        title = "Edge / Line Art",
        japaneseTag = "線画抽出",
        description = "Extracts clean anime ink contours using Sobel gradient operators.",
        defaultIntensity = 0.62f
    ),
    SKETCH(
        id = "SKETCH",
        title = "Manga Sketch",
        japaneseTag = "鉛筆素描",
        description = "Color-dodge graphite pencil shading with fine tonal grain.",
        defaultIntensity = 0.68f
    ),
    THRESHOLD(
        id = "THRESHOLD",
        title = "Binary Ink Threshold",
        japaneseTag = "二値化墨",
        description = "High-impact black & white manga ink separation.",
        defaultIntensity = 0.52f
    ),
    CONTRAST(
        id = "CONTRAST",
        title = "Dramatic Contrast",
        japaneseTag = "明暗強調",
        description = "Deepens shadow values and highlights for cel-shaded study.",
        defaultIntensity = 0.65f
    ),
    GRAYSCALE(
        id = "GRAYSCALE",
        title = "Tonal Grayscale",
        japaneseTag = "単色階調",
        description = "Balanced luminance conversion for value and form analysis.",
        defaultIntensity = 0.55f
    ),
    VIOLET_BLUEPRINT(
        id = "VIOLET_BLUEPRINT",
        title = "KAGAMI Violet Trace",
        japaneseTag = "紫電トレース",
        description = "Luminous electric-violet non-photo blue style underdrawing lines.",
        defaultIntensity = 0.64f
    );

    companion object {
        fun fromId(id: String): AutoDrawMode = entries.find { it.id == id } ?: ORIGINAL
    }
}

data class StrokeData(
    val points: List<Offset>,
    val colorArgb: Int,
    val strokeWidth: Float,
    val alpha: Float = 1f,
    val isEraser: Boolean = false,
    val isAutoGenerated: Boolean = false
)

object KagamiAutoDrawEngine {

    /**
     * Loads and downsamples a Bitmap safely from a content Uri or drawable resource
     * to prevent OutOfMemoryError while preserving crisp line resolution.
     */
    suspend fun loadOptimizedBitmap(
        context: Context,
        uri: Uri?,
        drawableResId: Int? = null,
        maxDimension: Int = 1080
    ): Bitmap? = withContext(Dispatchers.IO) {
        try {
            if (uri != null) {
                val boundsOptions = BitmapFactory.Options().apply { inJustDecodeBounds = true }
                context.contentResolver.openInputStream(uri)?.use {
                    BitmapFactory.decodeStream(it, null, boundsOptions)
                }
                val sampleSize = calculateInSampleSize(boundsOptions.outWidth, boundsOptions.outHeight, maxDimension)
                val decodeOptions = BitmapFactory.Options().apply {
                    inSampleSize = sampleSize
                    inPreferredConfig = Bitmap.Config.ARGB_8888
                }
                val decoded = context.contentResolver.openInputStream(uri)?.use {
                    BitmapFactory.decodeStream(it, null, decodeOptions)
                } ?: return@withContext null
                scaleDownIfNeeded(decoded, maxDimension)
            } else if (drawableResId != null) {
                val boundsOptions = BitmapFactory.Options().apply { inJustDecodeBounds = true }
                BitmapFactory.decodeResource(context.resources, drawableResId, boundsOptions)
                val sampleSize = calculateInSampleSize(boundsOptions.outWidth, boundsOptions.outHeight, maxDimension)
                val decodeOptions = BitmapFactory.Options().apply {
                    inSampleSize = sampleSize
                    inPreferredConfig = Bitmap.Config.ARGB_8888
                }
                val decoded = BitmapFactory.decodeResource(context.resources, drawableResId, decodeOptions)
                    ?: return@withContext null
                scaleDownIfNeeded(decoded, maxDimension)
            } else {
                null
            }
        } catch (e: Exception) {
            null
        }
    }

    private fun calculateInSampleSize(width: Int, height: Int, maxDim: Int): Int {
        var inSampleSize = 1
        if (height > maxDim || width > maxDim) {
            val halfHeight = height / 2
            val halfWidth = width / 2
            while ((halfHeight / inSampleSize) >= maxDim && (halfWidth / inSampleSize) >= maxDim) {
                inSampleSize *= 2
            }
        }
        return max(1, inSampleSize)
    }

    private fun scaleDownIfNeeded(source: Bitmap, maxDim: Int): Bitmap {
        val w = source.width
        val h = source.height
        if (w <= maxDim && h <= maxDim) return source
        val ratio = min(maxDim.toFloat() / w, maxDim.toFloat() / h)
        val targetW = max(1, (w * ratio).roundToInt())
        val targetH = max(1, (h * ratio).roundToInt())
        return Bitmap.createScaledBitmap(source, targetW, targetH, true)
    }

    /**
     * Processes the source Bitmap according to the selected AutoDrawMode and intensity (0.0f..1.0f).
     */
    suspend fun processImage(
        source: Bitmap,
        mode: AutoDrawMode,
        intensity: Float,
        invertOutput: Boolean = false
    ): Bitmap = withContext(Dispatchers.Default) {
        val clamped = intensity.coerceIn(0.05f, 1.0f)
        val w = source.width
        val h = source.height
        val inPixels = IntArray(w * h)
        source.getPixels(inPixels, 0, w, 0, 0, w, h)

        if (mode == AutoDrawMode.ORIGINAL && !invertOutput) {
            return@withContext source.copy(Bitmap.Config.ARGB_8888, false)
        }

        // Compute luminance array [0..255]
        val luma = IntArray(w * h)
        for (i in inPixels.indices) {
            val px = inPixels[i]
            val r = (px shr 16) and 0xFF
            val g = (px shr 8) and 0xFF
            val b = px and 0xFF
            luma[i] = (0.299f * r + 0.587f * g + 0.114f * b).roundToInt().coerceIn(0, 255)
        }

        val outPixels = IntArray(w * h)

        when (mode) {
            AutoDrawMode.ORIGINAL -> {
                for (i in inPixels.indices) {
                    val px = inPixels[i]
                    if (invertOutput) {
                        val r = 255 - ((px shr 16) and 0xFF)
                        val g = 255 - ((px shr 8) and 0xFF)
                        val b = 255 - (px and 0xFF)
                        outPixels[i] = (0xFF shl 24) or (r shl 16) or (g shl 8) or b
                    } else {
                        outPixels[i] = px
                    }
                }
            }

            AutoDrawMode.GRAYSCALE -> {
                // Intensity controls subtle gamma/Midtone weight (0.5 = neutral)
                val contrastBoost = 0.6f + clamped * 1.2f
                for (i in luma.indices) {
                    var v = (((luma[i] - 128) * contrastBoost) + 128).roundToInt().coerceIn(0, 255)
                    if (invertOutput) v = 255 - v
                    outPixels[i] = Color.rgb(v, v, v)
                }
            }

            AutoDrawMode.CONTRAST -> {
                // High-contrast S-curve / linear contrast factor on RGB + partial desaturation for anime look
                val factor = (1f + clamped * 2.4f)
                for (i in inPixels.indices) {
                    val px = inPixels[i]
                    val r0 = (px shr 16) and 0xFF
                    val g0 = (px shr 8) and 0xFF
                    val b0 = px and 0xFF
                    val l = luma[i]
                    // Blend 35% luma for crisp anime tonal feel
                    val rMix = r0 * 0.65f + l * 0.35f
                    val gMix = g0 * 0.65f + l * 0.35f
                    val bMix = b0 * 0.65f + l * 0.35f

                    var r = (((rMix - 128f) * factor) + 128f).roundToInt().coerceIn(0, 255)
                    var g = (((gMix - 128f) * factor) + 128f).roundToInt().coerceIn(0, 255)
                    var b = (((bMix - 128f) * factor) + 128f).roundToInt().coerceIn(0, 255)
                    if (invertOutput) {
                        r = 255 - r
                        g = 255 - g
                        b = 255 - b
                    }
                    outPixels[i] = Color.rgb(r, g, b)
                }
            }

            AutoDrawMode.THRESHOLD -> {
                // Cutoff threshold from 50..215 based on intensity
                val cutoff = (55 + (1f - clamped) * 150).roundToInt().coerceIn(25, 235)
                for (i in luma.indices) {
                    val isInk = luma[i] < cutoff
                    val inkColor = if (invertOutput) Color.WHITE else Color.rgb(12, 7, 22)
                    val paperColor = if (invertOutput) Color.rgb(8, 5, 16) else Color.WHITE
                    outPixels[i] = if (isInk) inkColor else paperColor
                }
            }

            AutoDrawMode.EDGE_OUTLINE, AutoDrawMode.VIOLET_BLUEPRINT -> {
                // Sobel 3x3 gradient operator
                val gain = 1.1f + clamped * 3.2f
                val noiseGate = ((1f - clamped) * 68f).roundToInt().coerceIn(8, 80)

                for (y in 1 until h - 1) {
                    val row = y * w
                    for (x in 1 until w - 1) {
                        val idx = row + x
                        val tl = luma[idx - w - 1]
                        val tc = luma[idx - w]
                        val tr = luma[idx - w + 1]
                        val ml = luma[idx - 1]
                        val mr = luma[idx + 1]
                        val bl = luma[idx + w - 1]
                        val bc = luma[idx + w]
                        val br = luma[idx + w + 1]

                        val gx = (-tl + tr - 2 * ml + 2 * mr - bl + br)
                        val gy = (-tl - 2 * tc - tr + bl + 2 * bc + br)
                        val mag = sqrt((gx * gx + gy * gy).toFloat()) / 4.0f
                        val boosted = if (mag < noiseGate) 0f else ((mag - noiseGate) * gain).coerceIn(0f, 255f)
                        val edgeStrength = (boosted / 255f).coerceIn(0f, 1f)

                        if (mode == AutoDrawMode.VIOLET_BLUEPRINT) {
                            if (invertOutput) {
                                // Dark OLED canvas with glowing violet/magenta lines
                                val r = (9 + edgeStrength * (167 - 9)).roundToInt().coerceIn(0, 255)
                                val g = (5 + edgeStrength * (139 - 5)).roundToInt().coerceIn(0, 255)
                                val b = (20 + edgeStrength * (250 - 20)).roundToInt().coerceIn(0, 255)
                                outPixels[idx] = Color.rgb(r, g, b)
                            } else {
                                // Clean white paper with crisp non-photo violet lines
                                val r = (255 - edgeStrength * (255 - 124)).roundToInt().coerceIn(0, 255)
                                val g = (255 - edgeStrength * (255 - 58)).roundToInt().coerceIn(0, 255)
                                val b = (255 - edgeStrength * (255 - 237)).roundToInt().coerceIn(0, 255)
                                outPixels[idx] = Color.rgb(r, g, b)
                            }
                        } else {
                            // Classic ink line art
                            var v = (255f * (1f - edgeStrength)).roundToInt().coerceIn(0, 255)
                            if (invertOutput) v = 255 - v
                            outPixels[idx] = Color.rgb(v, v, v)
                        }
                    }
                }
                // Fill 1px border cleanly
                val borderFill = if (invertOutput) Color.BLACK else Color.WHITE
                for (x in 0 until w) {
                    outPixels[x] = borderFill
                    outPixels[(h - 1) * w + x] = borderFill
                }
                for (y in 0 until h) {
                    outPixels[y * w] = borderFill
                    outPixels[y * w + (w - 1)] = borderFill
                }
            }

            AutoDrawMode.SKETCH -> {
                // Fast box blur on inverted luma + Color Dodge + subtle Sobel pencil reinforcement
                val invLuma = IntArray(w * h) { 255 - luma[it] }
                val radius = (2 + (clamped * 7).roundToInt()).coerceIn(2, 10)
                val blurredInv = boxBlurGrayscale(invLuma, w, h, radius)
                val pencilDarkness = 0.6f + clamped * 1.15f

                for (y in 1 until h - 1) {
                    val row = y * w
                    for (x in 1 until w - 1) {
                        val idx = row + x
                        val base = luma[idx]
                        val blur = blurredInv[idx]
                        val dodge = if (blur >= 255) 255 else min(255, (base shl 8) / (255 - blur + 1))

                        // Reinforce with subtle local gradient for crisp anime sketch lines
                        val gx = abs(luma[idx + 1] - luma[idx - 1])
                        val gy = abs(luma[idx + w] - luma[idx - w])
                        val edge = ((gx + gy) * pencilDarkness * 0.48f).roundToInt()

                        var sketchVal = (dodge - edge).coerceIn(0, 255)
                        // Apply gamma curve so pencil lines pop
                        val norm = (sketchVal / 255f)
                        sketchVal = (norm * norm * 255f).roundToInt().coerceIn(0, 255)
                        if (invertOutput) sketchVal = 255 - sketchVal
                        outPixels[idx] = Color.rgb(sketchVal, sketchVal, sketchVal)
                    }
                }
            }
        }

        val result = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888)
        result.setPixels(outPixels, 0, w, 0, 0, w, h)
        result
    }

    private fun boxBlurGrayscale(input: IntArray, width: Int, height: Int, radius: Int): IntArray {
        val temp = IntArray(width * height)
        val output = IntArray(width * height)
        val windowSize = radius * 2 + 1

        // Horizontal pass
        for (y in 0 until height) {
            var sum = 0
            val rowOffset = y * width
            for (i in -radius..radius) {
                val x = i.coerceIn(0, width - 1)
                sum += input[rowOffset + x]
            }
            for (x in 0 until width) {
                temp[rowOffset + x] = sum / windowSize
                val removeX = (x - radius).coerceIn(0, width - 1)
                val addX = (x + radius + 1).coerceIn(0, width - 1)
                sum += input[rowOffset + addX] - input[rowOffset + removeX]
            }
        }

        // Vertical pass
        for (x in 0 until width) {
            var sum = 0
            for (i in -radius..radius) {
                val y = i.coerceIn(0, height - 1)
                sum += temp[y * width + x]
            }
            for (y in 0 until height) {
                output[y * width + x] = sum / windowSize
                val removeY = (y - radius).coerceIn(0, height - 1)
                val addY = (y + radius + 1).coerceIn(0, height - 1)
                sum += temp[addY * width + x] - temp[removeY * width + x]
            }
        }
        return output
    }

    /**
     * Vectorizes strong edge contours from a reference Bitmap into ordered `StrokeData` paths
     * so KAGAMI can perform live animated Auto-Draw stroke plotting on the canvas!
     */
    suspend fun extractVectorAutoStrokes(
        source: Bitmap,
        intensity: Float,
        strokeColorArgb: Int,
        strokeWidth: Float,
        maxStrokes: Int = 260
    ): List<StrokeData> = withContext(Dispatchers.Default) {
        val w = source.width
        val h = source.height
        // Work on a normalized analysis grid (around 240px max dimension) for clean, smooth vector paths
        val targetDim = 240
        val scale = min(1f, targetDim.toFloat() / max(w, h))
        val gw = max(32, (w * scale).roundToInt())
        val gh = max(32, (h * scale).roundToInt())
        val scaled = Bitmap.createScaledBitmap(source, gw, gh, true)

        val pixels = IntArray(gw * gh)
        scaled.getPixels(pixels, 0, gw, 0, 0, gw, gh)

        val luma = IntArray(gw * gh)
        for (i in pixels.indices) {
            val px = pixels[i]
            val r = (px shr 16) and 0xFF
            val g = (px shr 8) and 0xFF
            val b = px and 0xFF
            luma[i] = (0.299f * r + 0.587f * g + 0.114f * b).roundToInt()
        }

        val edgeMap = BooleanArray(gw * gh)
        val threshold = (92 - (intensity.coerceIn(0.1f, 1f) * 58)).roundToInt().coerceIn(22, 95)

        for (y in 1 until gh - 1) {
            val row = y * gw
            for (x in 1 until gw - 1) {
                val idx = row + x
                val gx = -luma[idx - gw - 1] + luma[idx - gw + 1] -
                    2 * luma[idx - 1] + 2 * luma[idx + 1] -
                    luma[idx + gw - 1] + luma[idx + gw + 1]
                val gy = -luma[idx - gw - 1] - 2 * luma[idx - gw] - luma[idx - gw + 1] +
                    luma[idx + gw - 1] + 2 * luma[idx + gw] + luma[idx + gw + 1]
                val mag = hypot(gx.toDouble(), gy.toDouble()) / 4.0
                if (mag >= threshold) {
                    edgeMap[idx] = true
                }
            }
        }

        val visited = BooleanArray(gw * gh)
        val rawChains = mutableListOf<List<Offset>>()
        val invScaleX = w.toFloat() / gw.toFloat()
        val invScaleY = h.toFloat() / gh.toFloat()

        val dx = intArrayOf(1, 1, 0, -1, -1, -1, 0, 1)
        val dy = intArrayOf(0, 1, 1, 1, 0, -1, -1, -1)

        for (y in 1 until gh - 1) {
            for (x in 1 until gw - 1) {
                val startIdx = y * gw + x
                if (edgeMap[startIdx] && !visited[startIdx]) {
                    val chain = mutableListOf<Offset>()
                    var cx = x
                    var cy = y
                    visited[startIdx] = true
                    chain.add(Offset(cx * invScaleX, cy * invScaleY))

                    var keepTracing = true
                    while (keepTracing && chain.size < 90) {
                        keepTracing = false
                        for (dir in 0 until 8) {
                            val nx = cx + dx[dir]
                            val ny = cy + dy[dir]
                            if (nx in 1 until (gw - 1) && ny in 1 until (gh - 1)) {
                                val nIdx = ny * gw + nx
                                if (edgeMap[nIdx] && !visited[nIdx]) {
                                    visited[nIdx] = true
                                    cx = nx
                                    cy = ny
                                    chain.add(Offset(cx * invScaleX, cy * invScaleY))
                                    keepTracing = true
                                    break
                                }
                            }
                        }
                    }

                    if (chain.size >= 4) {
                        // Simplify/subsample every 2nd point for ultra-smooth Bezier rendering
                        val simplified = chain.filterIndexed { index, _ ->
                            index == 0 || index == chain.lastIndex || index % 2 == 0
                        }
                        if (simplified.size >= 2) {
                            rawChains.add(simplified)
                        }
                    }
                }
            }
        }

        // Prioritize longer structural contour lines first, then finer detail strokes
        rawChains
            .sortedByDescending { it.size }
            .take(maxStrokes)
            .map { points ->
                StrokeData(
                    points = points,
                    colorArgb = strokeColorArgb,
                    strokeWidth = strokeWidth,
                    alpha = 0.92f,
                    isEraser = false,
                    isAutoGenerated = true
                )
            }
    }

    /**
     * Composites the final artwork (Canvas Paper + Processed Reference Layer + User & Auto Strokes)
     * into a full-resolution Bitmap ready for saving or exporting.
     */
    fun renderCompositeBitmap(
        width: Int,
        height: Int,
        canvasBackgroundColorArgb: Int,
        processedReference: Bitmap?,
        referenceAlpha: Float,
        strokes: List<StrokeData>
    ): Bitmap {
        val safeW = max(1, width)
        val safeH = max(1, height)
        val output = Bitmap.createBitmap(safeW, safeH, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(output)

        // 1. Fill paper background
        canvas.drawColor(canvasBackgroundColorArgb)

        // 2. Draw processed reference / auto-draw image layer if present and visible
        if (processedReference != null && referenceAlpha > 0.01f) {
            val refPaint = Paint(Paint.ANTI_ALIAS_FLAG or Paint.FILTER_BITMAP_FLAG).apply {
                alpha = (referenceAlpha.coerceIn(0f, 1f) * 255).roundToInt()
            }
            val destRect = android.graphics.Rect(0, 0, safeW, safeH)
            canvas.drawBitmap(processedReference, null, destRect, refPaint)
        }

        // 3. Draw strokes on a dedicated transparent layer so Eraser (CLEAR xfermode) only erases strokes
        // and never punches black holes into the paper/reference!
        val strokeLayer = Bitmap.createBitmap(safeW, safeH, Bitmap.Config.ARGB_8888)
        val strokeCanvas = Canvas(strokeLayer)
        val paint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            style = Paint.Style.STROKE
            strokeCap = Paint.Cap.ROUND
            strokeJoin = Paint.Join.ROUND
        }

        for (stroke in strokes) {
            if (stroke.points.isEmpty()) continue
            paint.strokeWidth = stroke.strokeWidth
            if (stroke.isEraser) {
                paint.xfermode = PorterDuffXfermode(PorterDuff.Mode.CLEAR)
                paint.alpha = 255
            } else {
                paint.xfermode = null
                paint.color = stroke.colorArgb
                paint.alpha = (stroke.alpha.coerceIn(0.05f, 1f) * 255).roundToInt()
            }

            if (stroke.points.size == 1) {
                val pt = stroke.points.first()
                strokeCanvas.drawPoint(pt.x, pt.y, paint)
            } else {
                val path = Path()
                val first = stroke.points.first()
                path.moveTo(first.x, first.y)
                for (i in 1 until stroke.points.size) {
                    val prev = stroke.points[i - 1]
                    val curr = stroke.points[i]
                    val midX = (prev.x + curr.x) / 2f
                    val midY = (prev.y + curr.y) / 2f
                    path.quadTo(prev.x, prev.y, midX, midY)
                }
                val last = stroke.points.last()
                path.lineTo(last.x, last.y)
                strokeCanvas.drawPath(path, paint)
            }
        }

        canvas.drawBitmap(strokeLayer, 0f, 0f, null)
        return output
    }

    /**
     * Exports a Bitmap to the Android Gallery (`Pictures/KAGAMI`) using modern `MediaStore` APIs.
     */
    suspend fun exportToGallery(
        context: Context,
        bitmap: Bitmap,
        format: String,
        jpgQuality: Int,
        projectTitle: String
    ): Result<String> = withContext(Dispatchers.IO) {
        try {
            val isPng = format.uppercase() != "JPG"
            val ext = if (isPng) "png" else "jpg"
            val mimeType = if (isPng) "image/png" else "image/jpeg"
            val cleanTitle = projectTitle.replace(Regex("[^a-zA-Z0-9_-]"), "_").ifBlank { "KAGAMI_Art" }
            val filename = "${cleanTitle}_${System.currentTimeMillis()}.$ext"

            val resolver = context.contentResolver
            val contentValues = ContentValues().apply {
                put(MediaStore.Images.Media.DISPLAY_NAME, filename)
                put(MediaStore.Images.Media.MIME_TYPE, mimeType)
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                    put(MediaStore.Images.Media.RELATIVE_PATH, Environment.DIRECTORY_PICTURES + "/KAGAMI")
                    put(MediaStore.Images.Media.IS_PENDING, 1)
                }
            }

            val imageUri = resolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, contentValues)
                ?: return@withContext Result.failure(IllegalStateException("Unable to create MediaStore entry"))

            resolver.openOutputStream(imageUri)?.use { outStream ->
                val compressFormat = if (isPng) Bitmap.CompressFormat.PNG else Bitmap.CompressFormat.JPEG
                val quality = if (isPng) 100 else jpgQuality.coerceIn(60, 100)
                if (!bitmap.compress(compressFormat, quality, outStream)) {
                    return@withContext Result.failure(IllegalStateException("Bitmap compression failed"))
                }
            } ?: return@withContext Result.failure(IllegalStateException("Could not open output stream"))

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                contentValues.clear()
                contentValues.put(MediaStore.Images.Media.IS_PENDING, 0)
                resolver.update(imageUri, contentValues, null, null)
            }

            Result.success("Pictures/KAGAMI/$filename")
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    /**
     * Saves a Bitmap into internal app storage (`filesDir/kagami_projects`) for project persistence.
     */
    suspend fun saveInternalBitmap(
        context: Context,
        bitmap: Bitmap,
        filename: String
    ): String = withContext(Dispatchers.IO) {
        val dir = File(context.filesDir, "kagami_projects")
        if (!dir.exists()) dir.mkdirs()
        val file = File(dir, filename)
        FileOutputStream(file).use { out ->
            bitmap.compress(Bitmap.CompressFormat.PNG, 95, out)
        }
        file.absolutePath
    }

    /**
     * Serializes a list of `StrokeData` to compact JSON for Room storage.
     */
    fun serializeStrokesToJson(strokes: List<StrokeData>): String {
        val array = JSONArray()
        for (s in strokes) {
            val obj = JSONObject()
            obj.put("c", s.colorArgb)
            obj.put("w", s.strokeWidth.toDouble())
            obj.put("a", s.alpha.toDouble())
            obj.put("e", s.isEraser)
            obj.put("g", s.isAutoGenerated)
            val ptsArray = JSONArray()
            for (pt in s.points) {
                ptsArray.put((pt.x * 10f).roundToInt() / 10.0)
                ptsArray.put((pt.y * 10f).roundToInt() / 10.0)
            }
            obj.put("p", ptsArray)
            array.put(obj)
        }
        return array.toString()
    }

    /**
     * Deserializes `StrokeData` list from JSON string stored in Room.
     */
    fun deserializeStrokesFromJson(json: String): List<StrokeData> {
        if (json.isBlank()) return emptyList()
        return try {
            val array = JSONArray(json)
            val list = mutableListOf<StrokeData>()
            for (i in 0 until array.length()) {
                val obj = array.getJSONObject(i)
                val color = obj.optInt("c", Color.BLACK)
                val width = obj.optDouble("w", 8.0).toFloat()
                val alpha = obj.optDouble("a", 1.0).toFloat()
                val isEraser = obj.optBoolean("e", false)
                val isAuto = obj.optBoolean("g", false)
                val ptsArray = obj.optJSONArray("p")
                val points = mutableListOf<Offset>()
                if (ptsArray != null) {
                    var j = 0
                    while (j + 1 < ptsArray.length()) {
                        val x = ptsArray.getDouble(j).toFloat()
                        val y = ptsArray.getDouble(j + 1).toFloat()
                        points.add(Offset(x, y))
                        j += 2
                    }
                }
                if (points.isNotEmpty()) {
                    list.add(
                        StrokeData(
                            points = points,
                            colorArgb = color,
                            strokeWidth = width,
                            alpha = alpha,
                            isEraser = isEraser,
                            isAutoGenerated = isAuto
                        )
                    )
                }
            }
            list
        } catch (e: Exception) {
            emptyList()
        }
    }
}
